### ISSUE TITLE
你好你们给的HKU-IS显著性图不全

### ISSUE THREAD

**Issue by zzzppcc** [zal0302/CII#1]

**Comment by zal0302** [comment]
您好，HKU-IS数据集包括4447张图片，其中测试集包括1447张，通常只在HKU-IS测试集上进行测试，可参考issue（https://github.com/backseason/PoolNet/issues/18）以及其他开源方法给出的HKU-IS数据集结果。

**Comment by zal0302** [comment]
您好，HKU-IS数据集包括4447张图片，其中测试集包括1447张，通常只在HKU-IS测试集上进行测试，可参考其他开源方法给出的结果以及https://github.com/backseason/PoolNet/issues/18


> _No description provided._

**Comment by zal0302** [comment]
您好，HKU-IS数据集共包含4447张图像，其中测试集包括1447张样本，通常只在其测试集进行测试，可参考其他开源方法公开的HKU-IS数据集结果以及https://github.com/backseason/PoolNet/issues/18

**Comment by zal0302** [comment]
您好，HKU-IS数据集共包含4447张图像，其中测试集包括1447张样本，通常只在其测试集进行测试，可参考其他开源方法公开的HKU-IS数据集结果以及issue https://github.com/backseason/PoolNet/issues/18
