### ISSUE TITLE
关于RGC模块中参数共享的问题请教

### ISSUE THREAD

**Issue by abcxubu** [zal0302/CII#3]
十分感谢您Rethinking the U-Shape Structure for Salient Object Detection这个工作，从中学习了很多。在具体实现时，我有一个关于RGC模块中参数共享的问题：假设U型结构编码器各层的通道数分别为16,32,64,128和256，那么RGC模块的输入通道数和输出通道数都该是多大呢？比如对于通道数为256的层，它经过RGC模块输出的通道数要设成16吗？之后还需要把16通过1*1*1卷积变成256？希望得到您的回复，谢谢。

**Comment by zal0302** [comment]
感谢您对我们工作的关注和支持，由于RGC模块是参数共享的，所以需要把来自于编码器不同通道数的特征先通过1x1卷积变成同一通道数，再经过RGC模块进行处理。而处理后的特征没有经过1x1卷积，因为解码器对通道数没有特别的限制。
